<script setup lang="ts">
import { prices, whatsapp } from '~/data/site'
usePageSeo({ title:'Harga Service Laptop & Komputer Tangerang | KOMVEXA TECH', description:'Cek estimasi harga service laptop dan komputer Tangerang, mulai dari install Windows, cleaning, thermal paste, upgrade SSD/RAM, recovery data, hingga rakit PC.', path:'/harga', image:'/images/ssd-upgrade.png' })
const highlights = [['windows','Install Windows','Mulai Rp100.000','Sistem, driver, dan software dasar'],['spark','Cleaning Laptop','Mulai Rp75.000','Fan, heatsink, dan pembersihan debu'],['drive','Upgrade SSD','Jasa Rp100.000','Pemasangan, migrasi, dan testing']]
const estimatorServices = [{name:'Install Windows',price:100000},{name:'Cleaning Laptop',price:75000},{name:'Thermal Paste',price:100000},{name:'Upgrade SSD',price:100000},{name:'Upgrade RAM',price:75000},{name:'Recovery Data',price:200000},{name:'Rakit PC',price:250000}]
const selectedService = ref(0)
const device = ref('Laptop')
const urgency = ref('Normal')
const estimate = computed(() => estimatorServices[selectedService.value].price + (urgency.value === 'Prioritas' ? 50000 : 0))
const formattedEstimate = computed(() => new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(estimate.value))
const estimateWhatsapp = computed(() => `${whatsapp.split('?')[0]}?text=${encodeURIComponent(`Halo KOMVEXA TECH, saya ingin konsultasi ${estimatorServices[selectedService.value].name} untuk ${device.value} dengan pengerjaan ${urgency.value}.`)}`)
</script>

<template><div>
  <UiPageHero eyebrow="Harga" title="Estimasi jelas, tanpa kejutan." text="Ketahui kisaran biaya service sebelum pengerjaan. Harga final selalu dikonfirmasi setelah pemeriksaan."/>
  <section class="section price-page"><div class="container narrow">
    <div class="price-assurance"><span><BaseIcon name="shield"/><b>Harga transparan</b><small>Persetujuan sebelum pengerjaan</small></span><span><BaseIcon name="chat"/><b>Konsultasi gratis</b><small>Ceritakan gejalanya dahulu</small></span><span><BaseIcon name="check"/><b>Testing termasuk</b><small>Perangkat diuji sebelum selesai</small></span></div>
    <UiSectionHeading eyebrow="Layanan populer" title="Mulai dari kebutuhan yang paling umum." text="Harga berikut merupakan estimasi jasa dan dapat menyesuaikan kondisi perangkat." center/>
    <div class="price-highlights"><article v-for="(h,i) in highlights" :key="h[1]" :class="{featured:i===1}"><span v-if="i===1" class="popular-badge">PALING DIPILIH</span><div><BaseIcon :name="h[0]"/></div><h3>{{h[1]}}</h3><strong>{{h[2]}}</strong><p>{{h[3]}}</p><a :href="whatsapp">Konsultasikan <BaseIcon name="arrow" :size="16"/></a></article></div>
    <div class="estimator-section"><div class="estimator-copy"><span class="eyebrow">Estimator cepat</span><h2>Dapatkan gambaran biaya dalam beberapa klik.</h2><p>Pilih kebutuhan perangkat Anda. Hasil ini merupakan estimasi jasa awal dan belum termasuk sparepart.</p><div class="estimator-points"><span><BaseIcon name="check" :size="16"/> Tidak mengikat</span><span><BaseIcon name="shield" :size="16"/> Dikonfirmasi teknisi</span></div></div><div class="estimator-card"><div class="estimator-head"><span><i></i> QUICK ESTIMATE</span><b>LIVE</b></div><label>Jenis layanan<select v-model.number="selectedService"><option v-for="(service,i) in estimatorServices" :key="service.name" :value="i">{{service.name}}</option></select></label><div class="estimator-options"><label>Perangkat<select v-model="device"><option>Laptop</option><option>Komputer / PC</option></select></label><label>Pengerjaan<select v-model="urgency"><option>Normal</option><option>Prioritas</option></select></label></div><div class="estimate-result"><small>ESTIMASI JASA MULAI</small><strong>{{formattedEstimate}}</strong><span>*Belum termasuk sparepart dan biaya kunjungan.</span></div><a :href="estimateWhatsapp" target="_blank" rel="noopener" class="btn">Konsultasikan Estimasi <BaseIcon name="arrow" :size="17"/></a></div></div>
    <div class="price-table-wrap"><div class="price-table-title"><div><span>PRICE DATABASE</span><h2>Daftar estimasi layanan</h2></div><small>UPDATED // 2026</small></div><div class="price-table"><div class="table-head"><span>Layanan</span><span>Keterangan</span><span>Estimasi</span></div><div v-for="(p,i) in prices" :key="p[0]" class="table-row"><span><i>{{String(i+1).padStart(2,'0')}}</i><b>{{p[0]}}</b></span><span>{{p[1]}}</span><strong>{{p[2]}}</strong></div></div></div>
    <div class="notice"><BaseIcon name="shield"/><div><b>Catatan estimasi</b><p>Harga dapat berubah tergantung kerusakan, tipe perangkat, sparepart, lokasi, dan tingkat kesulitan. Kami selalu meminta persetujuan Anda sebelum pengerjaan.</p></div></div>
    <div class="simple-cta"><div><h3>Belum tahu layanan yang dibutuhkan?</h3><p>Ceritakan gejalanya kepada teknisi kami. Konsultasi awal gratis.</p></div><a :href="whatsapp" class="btn">Tanya Teknisi <BaseIcon name="arrow" :size="18"/></a></div>
  </div></section>
</div></template>
