<script setup lang="ts">
import { services, prices, portfolio, whatsapp } from '~/data/site'
usePageSeo({ title: 'Service Laptop & Komputer Tangerang | KOMVEXA TECH', description: 'Jasa service laptop dan komputer Tangerang untuk install Windows, upgrade SSD/RAM, cleaning, recovery data, rakit PC, dan service panggilan.', path: '/' })
const problems = [ ['clock','Laptop Lemot','Perangkat terasa lambat dan sering tidak responsif.'], ['temp','Laptop Panas','Suhu tinggi, kipas bising, atau mati mendadak.'], ['tool','Mati Total','Laptop atau PC tidak dapat dinyalakan.'], ['windows','Windows Error','Blue screen, gagal boot, atau sistem bermasalah.'], ['drive','Data Hilang','File terhapus atau storage tidak terbaca.'], ['chip','Upgrade Performa','Butuh RAM dan storage yang lebih cepat.'] ]
const process = ['Konsultasi','Pemeriksaan','Estimasi','Persetujuan','Pengerjaan','Testing','Selesai']
const portfolioImage = (type: string) => ({ cooling:'/images/laptop-cleaning-detail.png', ssd:'/images/ssd-upgrade.png', pc:'/images/pc-build.png' }[type] || '/images/technician-repairing-laptop.png')
</script>
<template>
  <div>
    <section class="home-hero"><div class="hero-grid-bg"></div><div class="container home-hero-grid">
      <div class="hero-content"><span class="eyebrow light"><i></i> Service laptop & komputer Tangerang</span><h1>Laptop bermasalah?<br><em>Kami bantu sampai normal kembali.</em></h1><p>Solusi terpercaya untuk kerusakan hardware, software, upgrade, dan maintenance. Diagnosa jelas, harga transparan, tanpa istilah yang membingungkan.</p><div class="hero-actions"><a :href="whatsapp" target="_blank" class="btn">Konsultasi Gratis <BaseIcon name="arrow" :size="18" /></a><NuxtLink to="/layanan" class="btn btn-ghost">Lihat Layanan</NuxtLink></div><div class="hero-trust"><span><BaseIcon name="check" :size="17" /> Diagnosa transparan</span><span><BaseIcon name="check" :size="17" /> Teknisi berpengalaman</span><span><BaseIcon name="check" :size="17" /> Konsultasi gratis</span></div></div>
      <div class="hero-visual hero-photo-wrap"><div class="visual-glow"></div><div class="hero-photo-frame"><img src="/images/technician-repairing-laptop.png" alt="Teknisi KOMVEXA memperbaiki laptop di meja kerja" width="1536" height="1152" fetchpriority="high"><span class="photo-badge"><i></i> Ditangani teknisi berpengalaman</span></div><div class="float-card fc-one"><BaseIcon name="shield" /><div><b>Diagnosa Akurat</b><small>Pemeriksaan menyeluruh</small></div></div><div class="float-card fc-two"><BaseIcon name="check" /><div><b>Siap Dikerjakan</b><small>Setelah Anda setuju</small></div></div></div>
    </div><div class="service-strip"><div class="container"><span>SERVICE LAPTOP</span><i></i><span>SERVICE PC</span><i></i><span>UPGRADE</span><i></i><span>INSTALL WINDOWS</span><i></i><span>HOME SERVICE</span></div></div></section>

    <section class="section"><div class="container"><UiSectionHeading eyebrow="Masalah perangkat" title="Ada masalah dengan perangkat Anda?" text="Kenali gejalanya. Kami bantu temukan solusi yang tepat tanpa membuat Anda bingung." center /><div class="problem-grid"><article v-for="p in problems" :key="p[1]" class="problem-card"><div><BaseIcon :name="p[0]" /></div><h3>{{ p[1] }}</h3><p>{{ p[2] }}</p><NuxtLink to="/kontak">Konsultasikan <BaseIcon name="arrow" :size="16" /></NuxtLink></article></div></div></section>

    <section class="section section-soft"><div class="container"><div class="heading-row"><UiSectionHeading eyebrow="Layanan unggulan" title="Semua kebutuhan perangkat, satu tempat." text="Dari perbaikan ringan hingga upgrade performa, ditangani dengan teliti." /><NuxtLink to="/layanan" class="text-link">Lihat semua layanan <BaseIcon name="arrow" :size="17" /></NuxtLink></div><div class="services-grid home-services"><UiServiceCard v-for="s in services.slice(0,6)" :key="s.title" :item="s" /></div></div></section>

    <section class="section why-section"><div class="container split-layout"><div class="tech-panel photo-panel"><img src="/images/laptop-cleaning-detail.png" alt="Proses pembersihan kipas laptop secara teliti" width="1536" height="1152" loading="lazy"><div class="photo-panel-shade"></div><div class="metric m1"><strong>500+</strong><span>Perangkat ditangani</span></div><div class="metric m2"><strong>98%</strong><span>Pelanggan puas</span></div><div class="photo-caption"><small>PROSES NYATA</small><b>Teliti sampai ke detail terkecil.</b></div></div><div><UiSectionHeading eyebrow="Mengapa kami" title="Perangkat Anda, kami tangani dengan serius." text="Kami percaya service yang baik dimulai dari komunikasi yang jujur." /><div class="feature-list"><article v-for="f in [['shield','Transparan','Informasi kerusakan dan biaya disampaikan sebelum pengerjaan.'],['tool','Profesional','Setiap tindakan disesuaikan dengan kondisi perangkat.'],['check','Aman & teliti','Data dan perangkat Anda diperlakukan dengan hati-hati.'],['chat','Mudah dipahami','Penjelasan sederhana tanpa istilah teknis berlebihan.']]" :key="f[1]"><div><BaseIcon :name="f[0]" /></div><span><b>{{ f[1] }}</b><small>{{ f[2] }}</small></span></article></div></div></div></section>

    <section class="section process-section"><div class="container"><UiSectionHeading eyebrow="Proses service" title="Mudah dari konsultasi hingga selesai." text="Setiap tahapan jelas. Anda selalu tahu apa yang sedang dikerjakan." center /><div class="process-line"><article v-for="(p,i) in process" :key="p"><span>{{ String(i+1).padStart(2,'0') }}</span><b>{{ p }}</b><i v-if="i < process.length-1"><BaseIcon name="arrow" :size="18" /></i></article></div></div></section>

    <section class="section section-soft"><div class="container pricing-preview"><div><UiSectionHeading eyebrow="Estimasi harga" title="Harga jelas sejak awal." text="Konsultasikan gejala perangkat Anda untuk estimasi yang lebih akurat." /><div class="mini-prices"><div v-for="p in prices.slice(0,5)" :key="p[0]"><span>{{ p[0] }}</span><strong>{{ p[2] }}</strong></div></div><NuxtLink to="/harga" class="btn btn-dark">Lihat Daftar Harga <BaseIcon name="arrow" :size="18" /></NuxtLink></div><div class="price-card"><span class="card-tag">PALING POPULER</span><div class="price-icon"><BaseIcon name="drive" :size="34" /></div><h3>Upgrade SSD Package</h3><p>Buat laptop lama terasa jauh lebih responsif untuk aktivitas sehari-hari.</p><ul><li><BaseIcon name="check" :size="17" /> Konsultasi kompatibilitas</li><li><BaseIcon name="check" :size="17" /> Pemasangan & testing</li><li><BaseIcon name="check" :size="17" /> Migrasi sistem jika memungkinkan</li></ul><small>Jasa mulai</small><strong class="big-price">Rp100.000</strong><em>*Harga SSD terpisah</em></div></div></section>

    <section class="section"><div class="container"><UiSectionHeading eyebrow="Hasil pengerjaan" title="Bukan sekadar janji. Lihat perubahannya." text="Beberapa hasil penanganan perangkat pelanggan kami." center /><div class="portfolio-mini"><article v-for="p in portfolio.slice(0,3)" :key="p.title"><div class="work-photo mini-work-photo"><img :src="portfolioImage(p.type)" :alt="`Hasil ${p.title}`" width="1536" height="1152" loading="lazy"><span class="work-result"><small>HASIL</small><strong>{{ p.stat }}</strong></span></div><span class="card-tag">{{ p.category }}</span><h3>{{ p.title }}</h3><p>{{ p.result }}</p></article></div><div class="center-action"><NuxtLink to="/portfolio" class="btn btn-outline">Lihat Semua Portofolio <BaseIcon name="arrow" :size="18" /></NuxtLink></div></div></section>

    <section class="section testimonials"><div class="container"><UiSectionHeading eyebrow="Cerita pelanggan" title="Kepercayaan yang kami jaga." center /><div class="testimonial-grid"><article v-for="t in [['Rizky Pratama','Laptop yang tadinya lemot setelah upgrade SSD jadi jauh lebih cepat. Prosesnya juga dijelaskan dengan jelas.'],['Andi Saputra','Service transparan, sebelum diperbaiki dikasih informasi biaya dulu. Sangat recommended!'],['Dimas Arya','Laptop panas sudah normal setelah cleaning dan thermal paste. Sekarang dipakai kerja nyaman lagi.']]" :key="t[0]"><div class="stars">★★★★★</div><p>“{{ t[1] }}”</p><div class="person"><span>{{ t[0].split(' ').map(x=>x[0]).join('') }}</span><div><b>{{ t[0] }}</b><small>Pelanggan KOMVEXA TECH</small></div></div></article></div></div></section>

    <section class="section cta-wrap"><div class="container"><div class="cta-panel"><div class="cta-pattern"></div><div><span class="eyebrow light">Konsultasi gratis</span><h2>Ceritakan masalah perangkat Anda.</h2><p>Kirim tipe perangkat dan gejalanya. Kami bantu arahkan solusi terbaiknya.</p></div><a :href="whatsapp" target="_blank" class="btn btn-white">Chat via WhatsApp <BaseIcon name="arrow" :size="18" /></a></div></div></section>
  </div>
</template>
