<script setup lang="ts">
import { whatsapp } from '~/data/site'
usePageSeo({title:'Kontak Website Portofolio & IT Support Tangerang | KOMVEXA TECH',description:'Hubungi KOMVEXA TECH untuk konsultasi website portofolio, IT support, service laptop dan komputer di Tangerang dan sekitarnya.',path:'/kontak'})
const areas=['Kota Tangerang','Karawaci','Cikokol','Cipondoh','Ciledug','Tangerang Selatan']
const contactWhatsapp = `${whatsapp.split('?')[0]}?text=${encodeURIComponent('Halo KOMVEXA TECH, saya ingin konsultasi tentang website portofolio atau IT support.')}`
</script>
<template><div class="contact-page">
  <UiPageHero eyebrow="Kontak" title="Mari bangun website dan dukung teknologi bisnis Anda." text="Ceritakan rencana website portofolio atau kebutuhan IT Anda. Tim kami siap membantu membahas langkah yang tepat."/>
  <section class="section contact-section"><div class="container contact-grid">
    <div class="contact-main"><UiSectionHeading eyebrow="Hubungi kami" title="Mulai dari cerita singkat." text="Pilih cara yang paling nyaman. Konsultasi awal bisa dimulai langsung lewat WhatsApp atau email."/>
      <a :href="contactWhatsapp" target="_blank" rel="noopener" class="contact-primary"><span class="wa-circle"><BaseIcon name="chat" :size="23"/></span><span class="contact-primary-copy"><small>RESPONS PALING CEPAT</small><b>Chat KOMVEXA di WhatsApp</b><em>0812-3456-7890 <BaseIcon name="arrow" :size="14"/></em></span><span class="contact-primary-arrow"><BaseIcon name="arrow" :size="20"/></span></a>
      <div class="contact-items"><a href="mailto:halo@komvexatech.com"><span class="contact-method-icon"><BaseIcon name="mail" :size="18"/></span><div><small>KIRIM EMAIL</small><b>halo@komvexatech.com</b></div><BaseIcon name="arrow" :size="15"/></a><div class="contact-prompt"><span class="contact-method-icon"><BaseIcon name="clock" :size="18"/></span><div><small>JAM LAYANAN</small><b>Senin–Sabtu, 09.00–19.00</b></div></div></div>
      <div class="contact-topics"><span><BaseIcon name="app" :size="15"/> Website Portofolio</span><span><BaseIcon name="chip" :size="15"/> IT Support</span></div>
    </div>
    <div class="hours-card contact-hours"><span class="contact-card-kicker"><i></i> KOMVEXA // TANGERANG</span><span class="eyebrow">Jam operasional</span><h2>Siap membantu bisnis Anda.</h2><p class="contact-hours-intro">Diskusikan kebutuhan website, kendala perangkat, atau layanan yang ingin Anda gunakan.</p><div class="hours-row"><span>Senin – Sabtu</span><b>09.00 – 19.00</b></div><div class="hours-row"><span>Minggu</span><b>Dengan perjanjian</b></div><a :href="contactWhatsapp" target="_blank" rel="noopener" class="contact-card-link">Mulai konsultasi <BaseIcon name="arrow" :size="16"/></a></div>
  </div></section>
  <section class="section section-soft contact-location-section"><div class="container location-grid"><div class="contact-area-copy"><UiSectionHeading eyebrow="Area layanan" title="Dekat dengan bisnis di Tangerang." text="Kami melayani Tangerang dan area sekitar. Kunjungan atau antar-jemput perangkat dapat dikonfirmasi saat konsultasi."/><div class="area-tags"><span v-for="a in areas" :key="a"><BaseIcon name="pin" :size="16"/>{{a}}</span></div></div><div class="map-card contact-map"><div class="map-grid"></div><div class="map-pin"><BaseIcon name="pin" :size="27"/></div><div class="map-label"><b>KOMVEXA TECH</b><small>Tangerang, Banten</small></div><a href="https://maps.google.com/?q=Tangerang" target="_blank" rel="noopener" class="btn btn-sm">Lihat area Tangerang <BaseIcon name="arrow" :size="16"/></a></div></div></section>
</div></template>
