<script setup lang="ts">
import { whatsapp } from '~/data/site'
usePageSeo({ title:'Tentang KOMVEXA TECH | Website Portofolio & IT Support', description:'Kenali KOMVEXA TECH, partner pembuatan website portofolio dan layanan IT support yang mengutamakan komunikasi jelas, pengerjaan teliti, dan solusi sesuai kebutuhan.', path:'/tentang', image:'/images/technician-repairing-laptop.png' })
const values = [['spark','Personal','Website dirancang mengikuti karakter dan kebutuhan bisnis Anda.'],['app','Responsif','Tampilan nyaman digunakan di ponsel, tablet, dan desktop.'],['shield','Transparan','Ruang lingkup dan estimasi dijelaskan sebelum pengerjaan.'],['chat','Konsultatif','Anda bisa berdiskusi dan memahami pilihan solusinya.']]
const methods = [['01','Pahami kebutuhan','Kami mulai dari tujuan website atau kendala perangkat Anda.'],['02','Susun solusi','Fitur, ruang lingkup, dan estimasi dibahas dengan jelas.'],['03','Kerjakan dengan teliti','Website dikembangkan responsif atau perangkat ditangani sesuai kebutuhan.'],['04','Uji dan serahkan','Kami memastikan hasil berfungsi baik sebelum diserahkan.']]
</script>
<template><div>
  <UiPageHero eyebrow="Tentang Kami" title="Website profesional. Dukungan teknologi yang jelas." text="Kami membantu bisnis tampil lebih meyakinkan melalui website portofolio, sekaligus siap mendukung kebutuhan IT dan perangkat Anda."/>
  <section class="section about-story"><div class="container about-editorial">
    <div class="about-photo"><img src="/images/technician-repairing-laptop.png" alt="Teknisi KOMVEXA TECH memeriksa laptop pelanggan" width="1536" height="1152"><span><i></i> DIGITAL & IT PARTNER</span><div><strong>Siap bantu</strong><small>Website • IT Support • Service</small></div></div>
    <div class="about-copy"><UiSectionHeading eyebrow="Cerita kami" title="Satu partner untuk kebutuhan digital dan IT."/><p class="body-lg">KOMVEXA TECH membantu bisnis membangun kehadiran online melalui website portofolio yang profesional dan mudah diakses.</p><p>Kami juga menyediakan dukungan IT, service, dan upgrade perangkat. Setiap kebutuhan dibahas dengan bahasa yang jelas, ruang lingkup yang terarah, dan perhatian pada detail.</p><div class="about-proof"><span><b>Website</b><small>Portofolio bisnis</small></span><span><b>Responsive</b><small>Untuk semua layar</small></span><span><b>IT Support</b><small>Untuk perangkat Anda</small></span></div><div class="signature">KOMVEXA <b>TECH</b><small>Website • Support • Service</small></div></div>
  </div></section>
  <section class="section section-soft"><div class="container"><UiSectionHeading eyebrow="Nilai utama" title="Dibuat dengan kebutuhan Anda sebagai fokus." text="Dari tampilan website sampai dukungan perangkat, setiap solusi dibuat agar mudah dipahami dan digunakan." center/><div class="values-grid"><article v-for="(v,i) in values" :key="v[1]"><span class="value-index">0{{i+1}}</span><div><BaseIcon :name="v[0]"/></div><h3>{{v[1]}}</h3><p>{{v[2]}}</p></article></div></div></section>
  <section class="section"><div class="container work-method modern-method"><div><UiSectionHeading eyebrow="Cara kami bekerja" title="Langkah jelas, hasil lebih terarah." text="Kami memastikan Anda memahami proses, ruang lingkup, dan hasil yang akan diterima."/><a :href="whatsapp" class="text-link">Diskusikan website atau IT support <BaseIcon name="arrow" :size="17"/></a></div><div class="method-list"><article v-for="m in methods" :key="m[0]"><span>{{m[0]}}</span><div><h3>{{m[1]}}</h3><p>{{m[2]}}</p></div></article></div></div></section>
</div></template>
