<script setup lang="ts">
import { whatsapp } from '~/data/site'
usePageSeo({ title:'Tentang KOMVEXA TECH | Teknisi Laptop Tangerang', description:'Kenali KOMVEXA TECH, partner service laptop dan komputer Tangerang yang mengutamakan diagnosa jelas, komunikasi jujur, keamanan perangkat, dan hasil teruji.', path:'/tentang', image:'/images/technician-repairing-laptop.png' })
const values = [['shield','Transparan','Hasil pemeriksaan dan estimasi biaya disampaikan sejak awal.'],['tool','Profesional','Pengerjaan teliti sesuai kebutuhan dan jenis kerusakan.'],['check','Aman','Perangkat serta data pelanggan diperlakukan dengan hati-hati.'],['chat','Konsultatif','Anda bebas bertanya dan memahami pilihan solusinya.']]
const methods = [['01','Dengarkan','Memahami keluhan dan kebutuhan perangkat Anda.'],['02','Periksa','Melakukan diagnosa secara teliti dan terarah.'],['03','Jelaskan','Menyampaikan solusi dan estimasi dengan bahasa sederhana.'],['04','Selesaikan','Mengerjakan, menguji, dan memastikan hasilnya optimal.']]
</script>
<template><div>
  <UiPageHero eyebrow="Tentang Kami" title="Teknologi yang rumit, dibuat sederhana." text="Kami hadir untuk membantu Anda memahami masalah perangkat dan mengambil keputusan perbaikan dengan tenang."/>
  <section class="section about-story"><div class="container about-editorial">
    <div class="about-photo"><img src="/images/technician-repairing-laptop.png" alt="Teknisi KOMVEXA TECH memperbaiki laptop" width="1536" height="1152"><span><i></i> WORKSHOP ACTIVE</span><div><strong>500+</strong><small>Perangkat ditangani</small></div></div>
    <div class="about-copy"><UiSectionHeading eyebrow="Cerita kami" title="Partner andal untuk perangkat sehari-hari."/><p class="body-lg">KOMVEXA TECH membantu menangani permasalahan software, hardware, upgrade, hingga maintenance laptop dan komputer.</p><p>Kami mengutamakan pemeriksaan yang jelas, komunikasi yang mudah dipahami, dan transparansi sebelum perbaikan dilakukan. Bagi kami, kepercayaan sama pentingnya dengan hasil pengerjaan.</p><div class="about-proof"><span><b>98%</b><small>Kepuasan pelanggan</small></span><span><b>7 tahap</b><small>Quality control</small></span><span><b>100%</b><small>Persetujuan dahulu</small></span></div><div class="signature">KOMVEXA <b>TECH</b><small>Repair • Upgrade • Support</small></div></div>
  </div></section>
  <section class="section section-soft"><div class="container"><UiSectionHeading eyebrow="Nilai utama" title="Prinsip yang kami pegang." text="Standar sederhana yang kami terapkan pada setiap perangkat." center/><div class="values-grid"><article v-for="(v,i) in values" :key="v[1]"><span class="value-index">0{{i+1}}</span><div><BaseIcon :name="v[0]"/></div><h3>{{v[1]}}</h3><p>{{v[2]}}</p></article></div></div></section>
  <section class="section"><div class="container work-method modern-method"><div><UiSectionHeading eyebrow="Cara kami bekerja" title="Kami tidak sekadar memperbaiki." text="Kami memastikan Anda memahami masalah, solusi, dan hasil akhirnya."/><a :href="whatsapp" class="text-link">Diskusikan perangkat Anda <BaseIcon name="arrow" :size="17"/></a></div><div class="method-list"><article v-for="m in methods" :key="m[0]"><span>{{m[0]}}</span><div><h3>{{m[1]}}</h3><p>{{m[2]}}</p></div></article></div></div></section>
  <section class="section cta-wrap"><div class="container"><div class="cta-panel"><div><span class="eyebrow light">Siap membantu</span><h2>Ada yang ingin ditanyakan?</h2><p>Konsultasikan masalah perangkat Anda tanpa biaya.</p></div><a :href="whatsapp" class="btn btn-white">Mulai Konsultasi <BaseIcon name="arrow" :size="18"/></a></div></div></section>
</div></template>
